services:
  - type: web
    name: uptime-kuma
    env: docker
    repo: https://github.com/anastasovPetar/UpTime-Kuma
    branch: main
    plan: starter # or standard if you need persistent disk
    dockerfilePath: Dockerfile
    healthCheckPath: /
    autoDeploy: true
    disks
      - name: uptime-kuma-data
        mountPath: /app/data
        sizeGB: 1
    envVars:
      - key: PORT
        value: 3001
