services:
  - type: web
    name: uptime-kuma
    env: docker
    repo: https://github.com/YOUR_USER/uptime-kuma-render
    branch: main
    plan: starter # or standard if you need persistent disk
    dockerfilePath: Dockerfile
    healthCheckPath: /
    autoDeploy: true
    diskMountPath: /app/data
